config/routes.rb
Rails.application.routes.draw do

  resources :checkouts

  resources :cart_items

  resources :carts
  resources :products

  get 'session/login'
  post 'session/create'
  delete 'session/logout'

  resources :users

  root 'products#index'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  first_name      :string
#  last_name       :string
#  email           :string
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  admin           :boolean          default(FALSE)
#

class User < ActiveRecord::Base

  has_secure_password

  has_many :carts
  has_one :checkout

  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :email

  validates_format_of :email, with: /[a-zA-z0-9]+@[a-zA-Z0-9]+\.[a-zA-z0-9]+/

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authorize_admin, only: [:index]
  before_action :authorize_user, only: [:show, :edit, :update]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)



    respond_to do |format|
      if @user.save

        @cart = @user.carts.create(subtotal: 0, status: true)

        if @cart.save
          session[:user_id] = @user.id
          format.html { redirect_to @user, notice: 'Thanks for signing up! Now get shopping.' }
          format.json { render :show, status: :created, location: @user }
        end
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy

    @user.carts.each do |cart|
      cart.cart_items.each do |item|
        item.destroy
      end
      cart.destroy
    end

    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :first_name %><br>
      <%= f.text_field :first_name %>
    </div>

    <div class="field">
      <%= f.label :last_name %><br>
      <%= f.text_field :last_name %>
    </div>

    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>

    <div class="field">
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Back to Account Info', @user %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>ID</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.id %></td>
        <td></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Main Page', products_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h3>Your Info</h3>
<hr>

<% if current_user  %>
    <% if current_user.admin  %>
        <h5>You are an administrator.</h5>
    <% end  %>
<% end  %>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>User ID:</strong>
  <%= @user.id %>
</p>

<%= link_to 'Edit Account Info', edit_user_path(@user) %><br>
<% if @user.checkout !=nil %>
    <%= link_to 'Edit Saved Checkout Info', edit_checkout_path(@user.checkout) %><br>
    <%= link_to 'Delete Saved Checkout Info', @user.checkout, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end  %>
<br>
<br>

<h3>Your Orders</h3>

<hr>

<% @user.carts.reverse.each do |cart| %>

    <p>
      <strong>Order Number:</strong>
      <%= cart.id %>
    </p>

    <p>
      <strong>Status:</strong>
      <% if cart.status %>
        Active
      <% else %>
        Completed
      <% end %>
    </p>

    <p>
      <strong>Subtotal:</strong>
      <%= cart.subtotal %>
    </p>

    <% if cart.status  %>
         <%= link_to 'View Current Cart', cart %>
    <% else  %>
        <%= link_to 'View Receipt', cart %>
    <% end  %>

    <p>
      -----------------------------------------
    </p>

    <% end %>