config/routes.rb
Rails.application.routes.draw do

  resources :checkouts

  resources :cart_items

  resources :carts
  resources :products

  get 'session/login'
  post 'session/create'
  delete 'session/logout'

  resources :users

  root 'products#index'

end

app/models/cart.rb
# == Schema Information
#
# Table name: carts
#
#  id            :integer          not null, primary key
#  subtotal      :decimal(10, 2)
#  status        :boolean
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  user_id       :integer
#  cart_items_id :integer
#

class Cart < ActiveRecord::Base

  belongs_to :user

  has_many :cart_items
  has_one :checkout

  def update_subtotal
    subtotal = 0

    self.cart_items.each do |cart_item|
      subtotal = subtotal + cart_item.product.price * cart_item.quantity
    end

    self.subtotal = subtotal
    self.save
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  before_action :authorize_cart, only: [:show, :edit, :update, :destroy]
  before_action :authorize_admin, only: [:index]
  before_action :authorize, only: [:new]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit(:subtotal, :status)
    end


end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subtotal %><br>
    <%= f.text_field :subtotal %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Carts</h1>

<table>
  <thead>
    <tr>
      <th>Subtotal</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= cart.subtotal %></td>
        <td><%= cart.status %></td>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<% if @cart.status %>
<% else  %>
    <div style="float:none">
      <div style="text-align: center;"><h3>This is the receipt for your order. Thanks!</h3></div>
    </div>
<% end %>

<p>
  <strong>Order Number:</strong>
  <%= @cart.id %>
</p>

<p>
  <strong>Status:</strong>
  <% if @cart.status %>
      Active<br>
  <% else %>
      Completed<br>

  <% end %>
  <hr>
</p>

<p>

  <% if @cart.cart_items.count == 0  %>
    <h5>There are no items in your cart!</h5>

<% else  %>

<table>
  <thead>
  <tr>
    <th>Item</th>
    <th></th>
    <th></th>
    <th>Price</th>
    <th colspan="5"></th>
  </tr>
  </thead>

  <tbody>
  <% @cart.cart_items.each do |cart_item| %>

    <tr>
        <td><%= link_to cart_item.product.title, cart_item.product %></td>
        <td></td>
        <td></td>
        <td align="right"> <%= cart_item.product.price %></td>
        <td></td>
      <% if @cart.status  %>
        <td><%= button_to 'Remove. Please don\'t click this.', cart_item, method: :delete %></td>
      <% end  %>
    </tr>
  <% end %>
  </tbody>
</table>

</p>



  <table>
    <thead>
    <tr>

      <% if @cart.status %>
            <th>Subtotal:</th>
      <% else  %>
            <th>Total:</th>
      <% end %>
      <th></th>
      <th></th>
      <th align="right"><%= @cart.subtotal %></th>
    </tr>
    </thead>
  </table>


<% end  %>

<br>
<br>

<% if @cart.status  %>
    <%= link_to 'Keep Shopping! Buy More Things!', root_path %>
    <br>
    <br>
    <!--<%= link_to 'Checkout', new_checkout_path %>-->
    <!--<br>-->
    <!--<br>-->
    <!--<%= button_to 'Checkout', new_checkout_path(user_id: @cart.user, cart_id: @cart), method: :post %>-->
    <%= button_to 'Checkout', new_checkout_path, method: :get %>
      <br>
      <br>

<% else %>
    <hr><br>
    <strong>Order Placed On:  </strong><%= @cart.checkout.created_at  %><br>
    <strong>Billed To:  </strong><%= @cart.checkout.billname  %><br>
    <strong>Card Ending In:  </strong><%= @cart.checkout.cardnumber[-4 .. -1]  %><br>
      <br>
    <strong>Shipped To:  </strong><%= @cart.checkout.shipname %>, <%= @cart.checkout.shipstreet %>, <%= @cart.checkout.shipcity %>, <%= @cart.checkout.shipstate %> <%= @cart.checkout.shipzip %><br>



<% end %>

<br>

<%= link_to 'Back to Account Info', current_user, method: :get %>