config/routes.rb
Rails.application.routes.draw do

  resources :checkouts

  resources :cart_items

  resources :carts
  resources :products

  get 'session/login'
  post 'session/create'
  delete 'session/logout'

  resources :users

  root 'products#index'

end

app/models/cart_item.rb
# == Schema Information
#
# Table name: cart_items
#
#  id         :integer          not null, primary key
#  product_id :integer
#  cart_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  quantity   :integer          default(1)
#

class CartItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :set_cart_item, only: [:show, :edit, :update, :destroy]
  before_action :authorize, only: [:create]
  before_action :authorize_admin, only: [:show, :edit, :update, :destroy]

  # GET /cart_items
  # GET /cart_items.json
  def index
    @cart_items = CartItem.all
  end

  # GET /cart_items/1
  # GET /cart_items/1.json
  def show
  end

  # GET /cart_items/new
  def new
    @cart_item = CartItem.new
  end

  # GET /cart_items/1/edit
  def edit
  end

  # POST /cart_items
  # POST /cart_items.json
  def create
    @cart_item = CartItem.new(product_id: cart_item_params[:product_id], cart_id: cart_item_params[:cart_id])

    # @cart_item = CartItem.new(cart_item_params)


    @cart = Cart.find(cart_item_params[:cart_id])

    # @cart = cart_item_params[:cart_id]
    # @cart = @cart_item.cart



      respond_to do |format|
        if @cart_item.save

          # @cart = @cart_item.cart_id

          @cart.update_subtotal

          format.html { redirect_to @cart, notice: 'You put the thing in your cart. You\'re awesome.' }
          format.json { render :show, status: :created, location: @cart }
        else
          format.html { render :new }
          format.json { render json: @cart_item.errors, status: :unprocessable_entity }
        end
      end



  end

  # PATCH/PUT /cart_items/1
  # PATCH/PUT /cart_items/1.json
  def update
    respond_to do |format|
      if @cart_item.update(cart_item_params)
        format.html { redirect_to @cart_item, notice: 'Cart item was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart_item }
      else
        format.html { render :edit }
        format.json { render json: @cart_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cart_items/1
  # DELETE /cart_items/1.json
  def destroy

    @cart = @cart_item.cart
    @cart_item.destroy
    @cart.update_subtotal

    respond_to do |format|
      format.html { redirect_to @cart, notice: 'I can\'t believe you took that thing out of your cart. Jerk.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart_item
      @cart_item = CartItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_item_params
      params.permit(:product_id, :cart_id)
    end


end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/_form.html.erb
<%= form_for(@cart_item) do |f| %>
  <% if @cart_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart_item.errors.count, "error") %> prohibited this cart_item from being saved:</h2>

      <ul>
      <% @cart_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= product.id %>
<%= cart.id %>
<%= @cart_item.id %>

  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>

    <%= f.hidden_field :product_id, value: product.id %>
    <%= f.hidden_field :cart_id, value: cart.id %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cart_items/edit.html.erb
<h1>Editing Cart Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart_item %> |
<%= link_to 'Back', cart_items_path %>

app/views/cart_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cart Items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cart_items.each do |cart_item| %>
      <tr>
        <td><%= cart_item.product %></td>
        <td><%= cart_item.cart %></td>
        <td><%= link_to 'Show', cart_item %></td>
        <td><%= link_to 'Edit', edit_cart_item_path(cart_item) %></td>
        <td><%= link_to 'Destroy', cart_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart item', new_cart_item_path %>

app/views/cart_items/new.html.erb
<h1>New Cart Item</h1>

<%= render 'form' %>

<%= link_to 'Back', cart_items_path %>

app/views/cart_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @cart_item.product %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @cart_item.cart %>
</p>

<%= link_to 'Edit', edit_cart_item_path(@cart_item) %> |
<%= link_to 'Back', cart_items_path %>